spring:
  application:
    name: parcel-station
  datasource:
    url: jdbc:mysql://localhost:3306/parcel_station?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
